services:
  postgres:
    image: postgres:18-alpine3.23
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: auth
    ports:
      - "5432:5432"

  redis:
    image: redis:8.6-alpine3.23
    ports:
      - "6379:6379"

  auth:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
